      -1 Call: icpp [Option] <Source file> [Option] <Output file> [Option]
        /D <Name>      #define name
        /I <Pfad>      path for include files
        /E             Output to stdout
MEGA_INCLUDE_PATH      Environment: Search path for #include ...

    1601 ')' missing

    1602 Could not find line end when reloading

    1603 argument missing

    1801 expect operand

    1802 expect operation

    1803 expect ';'

    1804 expect ','

    1805 expect '['

    1806 expect ']'

    1807 expect '('

    1808 expect ')'

    1809 expect '}'

    1810 expect '{'

    1811 expect '"' or '<'

    1812 expect '>'

    1823 expect name

    1824 expect key word

    1825 expect type specification

    1827 expect Ausdruck after assignment

    1828 expect constant Ausdruck

    1831 operands must be of same type

    1834 expect number larger than zero

    1835 expect natural number or variable

    1836 expect character

    1837 expect hexadecimal number

    1838 expect line end

    1839 expect letter

    1840 expect path name after #include

    1860 unexpected: '('

    1861 unexpected: ')'

    1867 unexpected: '#elif'

    1868 unexpected: '#endif'

    1871 unexpected: ','

    1872 unexpected character in #define ...

    1873 unexpected character: '%s'

    1874 unexpected: '{'

    1877 unexpected word: '%s'

    2001 unknown option: '%s'

    2002 file name after #include missing

    2003 can't write data

    2005 could not read file '%s'

    2006 could not open file '%s'

    2007 could not find file '%s'

    2009 no Output file created

    2010 no memory available

    2012 #error: %s

    2013 text position cannot be interpreted

    2016 type conflict

    2018 cast not legal

    2023 multiply defined

    2025 variable is not from type 'struct'

    2026 error within expression

    2031 number is outside of legal range

    2032 string is too long

    2033 too many parameters

    2034 not enough parameters

    2037 operation '&' not possible

    2038 operation '*' not possible

    2039 operation '[..]' not possible

    2040 division by zero

    2042 Operands have different types

    2046 Constant must not be changed

    2049 String includes LF

    2207 Limit: Function was declared with more than 15 parameters

    2210 Operating system does not support available memory anymore

    2213 Limit: Line to long

    2215 Integer-constant to large

    2216 Double-constant zu large

    2217 Double-Exponent to large

    2218 Limit: To many '#if'

    2219 Limit: To many '#ifdef'

    2220 Limit: To many '#ifndef'

    2221 Limit: Include path is to long.

    2222 Limit: Structure depth of #include is max. 10

    2223 Limit: Structure depth of #if is max. 200

    2227 Not enough memory to expand macro

    2410 Operand to 'unsigned' converted
